apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-central-station
  labels:
    app: base-central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-central-station
  template:
    metadata:
      name: base-central-station
      labels:
        app: base-central-station
    spec:
      containers:
        - name:  base-central-station
          image: mariamelsamni/weather-system-base-central-station:v1.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: parquet-volume
              mountPath: /app/weather/
            - name: bitcask-volume
              mountPath: /app/bitcask_store/
      restartPolicy: Always
      volumes:
        - name: parquet-volume
          persistentVolumeClaim:
            claimName: pvc-parquet
        - name: bitcask-volume
          persistentVolumeClaim:
            claimName: pvc-bitcask

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-parquet
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bitcask
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi