apiVersion: v1
kind: ConfigMap
metadata:
  name: station-id-config
data:
  station-id-0: "1"
  station-id-1: "2"
  station-id-2: "3"
  station-id-3: "4"
  station-id-4: "5"
  station-id-5: "6"
  station-id-6: "7"
  station-id-7: "8"
  station-id-8: "9"
  station-id-9: "10"
