version: '3.3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  base-cental-station:
    build: Base-Central-Station/
    networks:
      - kafka-network
    volumes:
      - parquet-volume:/app/weather_data

  parquet-elasticsearch-connector:
    build: connectorr/
    networks:
      - elastic-network
    volumes:
      - parquet-volume:/app/weather_data

  elasticsearch:
    container_name: elasticsearch
    build: elastic-search
    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
#      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms4g -Xmx10g"
      - "ES_PORT=9200"
      - "ES_JAVA_HOME=/usr/share/elasticsearch/jdk"
    mem_limit: 4g
    networks:
      - elastic-network
#

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=wJ$7mQ^E5#6@8zL!x0*rYpUvD4&9%2Qt"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

volumes:
  parquet-volume:

networks:
  kafka-network:
    driver: bridge
  elastic-network:
    driver: bridge
